# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
   gcp-cli: circleci/gcp-cli@1.0.0
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  install_and_configure_cli:
    # Run the welcome/run job in its own container
    jobs:
      - gcp-cli/install_and_initialize_cli:
          context: myContext
          executor: gcp-cli/default